version: '3'
services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mediawiki

  wiki:
    image: radiorabe/mediawiki:latest
    build: ./wiki
    ports:
      - "8081:80"
    environment:
      MW_WG_SERVER: ~
      MW_WG_DBUSER: root
      MW_WG_DBPASS: secret
      MW_WG_LANGUAGECODE: en
      MW_WG_RAWHTML: 'false'
      MW_WG_SECRET: ~
    volumes:
      - ./images:/var/www/html/images

  parsoid:
    image: benhutchins/parsoid:latest
    volumes:
      - "./parsoid/:/data/"
