version: '3'
services:
  mysql:
    volumes:
      # mount for keeping backups
      # - /var/lib/backups/mysql:/var/lib/backups/
    environment:
      MYSQL_ROOT_PASSWORD: secret
  wiki:
    volumes:
      # Mount for images
      #- /var/lib/images/:/var/www/html/images
      # mount for keeping backups
      # - /var/lib/backups/images:/var/lib/backups/
    environment:
      VIRTUAL_HOST: wiki.vcap.me
      # external server name
      MW_WG_SERVER: http://wiki.vcap.me:8081
      # Changeme
      # MW_WG_SECRET: ""
      MW_WG_SITENAME: RaBeWiki
      MW_WG_METANAMESPACE: RaBeWiki
      MW_WG_DBUSER: root
      MW_WG_DBPASS: secret
      MW_WG_LANGUAGECODE: de-ch
      MW_WG_RAWHTML: 'true'
      # REMOTE_USER login only
      MW_AUTH_CREATEACCOUNT: 'false'
      MW_AUTH_REMOTEUSER: 'true'
      # Activate Maintenance mode
      # MW_WG_READONLY: "Maintenance"
      # Activate debug
      # MW_DEBUG: "true"
  # parsoid is currently configured with sane defaults by the config in the parsoid subdirectory
  # It is not exposed except through this mediawiki instance. As such you probably don't need to
  # override anything below.
  #parsoid:
  #  environment:
  #    VIRTUAL_HOST: parsoid.vcap.me
